// ============================================================
//  言語設定（JA / EN）
// ============================================================
window.LANG = localStorage.getItem('fruitBubbleLang') || 'ja';

window.T = {
  ja: {
    score:          'スコア',
    best:           'ベスト',
    next:           'NEXT',
    danger:         'DANGER',
    tapHint:        '✦ タップでレーン選択 ✦',
    paused:         '一時停止',
    feverEnd:       'フィーバー終了',
    scoreX2:        'スコア 2倍!!',
    pushAll:        '⬆ 5個 一斉にせり上がる！',
    push1:          '⬆ 1個 どこかにせり上がる！',
    pushNext:       '⬆ つぎに押し上がる',
    gameOver:       'ゲームオーバー',
    playAgain:      'もう一度プレイ',
    share:          '📤 スコアをシェア',
    langBtn:        '🌐 EN',
    restartBtn:     '↺',
    restartConfirm: 'ほんとにやり直す？',
    restartYes:     'やり直す',
    restartNo:      'キャンセル',
    helpBtn:        '？',
    helpTitle:      '🍓 あそびかた',
    howToPlay: [
      '🎯 上のフルーツをタップして\n　 好きなレーンに落とそう',
      '🍇 同じフルーツが 3つ以上\n　 縦か横に並ぶと消える！',
      '👑 王冠フルーツは 2個並ぶだけで\n　 消えてレアフルーツに合体！',
      '✨ 消えるときコンボすると\n　 大きいフルーツに合体！',
      '⬆ 10秒ごとに下から\n　 フルーツが押し上がってくる',
      '💀 フィールドがいっぱいに\n　 なるとゲームオーバー',
      '💖 フィーバータイムは\n　 スコア 2倍のチャンス！',
    ],
    helpClose:      '閉じる',
    reviveBtn:      '📺 動画を見て復活！',
    reviveWatching: '動画を読み込み中...',
    reviveNotAvail: '広告がありません',
    badgeBtn:       '🏅',
    badgeTitle:     '🏅 バッジコレクション',
    badgeNew:       '🎊 バッジ獲得！',
    badgeEarned:    '獲得済み',
    badgeProgress:  (n, t) => `${n} / ${t} 獲得`,
    badgeClose:     '閉じる',
    nextRank:  (pts) => `あと ${pts.toLocaleString()} pt でランクアップ！`,
    ranks: [
      { threshold: 0,       name: 'ビギナー',         emoji: '🌱' },
      { threshold: 500,     name: 'ルーキー',         emoji: '🍇' },
      { threshold: 2000,    name: 'アマチュア',       emoji: '🍊' },
      { threshold: 5000,    name: 'セミプロ',         emoji: '🍎' },
      { threshold: 15000,   name: 'プロ',             emoji: '🍋' },
      { threshold: 50000,   name: 'マスター',         emoji: '🍍' },
      { threshold: 150000,  name: 'グランドマスター', emoji: '🍉' },
      { threshold: 500000,  name: 'レジェンド',       emoji: '🌈' },
    ],
  },
  en: {
    score:     'Score',
    best:      'Best',
    next:      'NEXT',
    danger:    'DANGER',
    tapHint:   '✦ Tap to drop here ✦',
    paused:    'PAUSED',
    feverEnd:  'FEVER END',
    scoreX2:   'Score x2!!',
    pushAll:   '⬆ All 5 rising up!',
    push1:     '⬆ 1 surprise fruit!',
    pushNext:  '⬆ Next push',
    gameOver:  'GAME OVER',
    playAgain: 'Play Again',
    share:     '📤 Share Score',
    langBtn:        '🌐 JP',
    restartBtn:     '↺',
    restartConfirm: 'Really restart?',
    restartYes:     'Restart',
    restartNo:      'Cancel',
    helpBtn:        '?',
    helpTitle:      '🍓 How to Play',
    howToPlay: [
      '🎯 Tap the fruit at the top\n   to drop it into a lane',
      '🍇 3+ matching fruits in a row\n   or column disappear!',
      '👑 Crown fruits need only 2\n   in a row to merge!',
      '✨ Chain combos to merge\n   into bigger fruits!',
      '⬆ Every 10s, fruits push up\n   from the bottom',
      '💀 Game over when the\n   field fills to the top',
      '💖 Fever Time doubles\n   your score — go for it!',
    ],
    helpClose:      'Close',
    reviveBtn:      '📺 Watch Ad & Revive!',
    reviveWatching: 'Loading ad...',
    reviveNotAvail: 'Ad not available',
    badgeBtn:       '🏅',
    badgeTitle:     '🏅 Badge Collection',
    badgeNew:       '🎊 Badge Earned!',
    badgeEarned:    'Earned',
    badgeProgress:  (n, t) => `${n} / ${t} Earned`,
    badgeClose:     'Close',
    nextRank:  (pts) => `${pts.toLocaleString()} pts to rank up!`,
    ranks: [
      { threshold: 0,       name: 'Beginner',    emoji: '🌱' },
      { threshold: 500,     name: 'Rookie',      emoji: '🍇' },
      { threshold: 2000,    name: 'Amateur',     emoji: '🍊' },
      { threshold: 5000,    name: 'Semi-Pro',    emoji: '🍎' },
      { threshold: 15000,   name: 'Pro',         emoji: '🍋' },
      { threshold: 50000,   name: 'Master',      emoji: '🍍' },
      { threshold: 150000,  name: 'Grand Master',emoji: '🍉' },
      { threshold: 500000,  name: 'Legend',      emoji: '🌈' },
    ],
  },
};

// 現在の言語テキストを返すショートカット
window.t = () => window.T[window.LANG];
